package model.entities;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.AttributeList;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

/**
 * Employee Entity Object - Created by Mike H. (2000)
 *
 * This was the very first Entity Object in BurgerQuick. I built it following
 * the ADF tutorial. Keeping it simple - one EO per table, no fancy inheritance.
 *
 * - Mike
 */
public class EmployeeEOImpl extends EntityImpl {

    // Mike's convention: prefixes for everything. It's clear.
    // (Sarah later said this is verbose. She uses shorter names. Both are fine.)
    private static final int EMPLOYEE_ID = 0;
    private static final int FIRST_NAME = 1;
    private static final int LAST_NAME = 2;
    private static final int SSN = 3;
    private static final int HIRE_DATE = 4;
    private static final int STORE_NUMBER = 5;
    private static final int POSITION = 6;
    private static final int HOURLY_RATE = 7;
    private static final int MANAGER_ID = 8;
    private static final int PHONE = 9;
    private static final int IS_ACTIVE = 10;

    // Mike stored SSN in plain text. It was 2000. Nobody thought about it.
    // 2018 security audit flagged this as CRITICAL.
    // 2019: Marcus started encrypting SSN in the USERS table (abandoned project).
    // 2020: Still plain text. We don't touch legacy columns.
    // 2022: Audit flag downgraded to "accepted risk" by CISO.

    /**
     * Gets the employee's full name by concatenating first and last.
     * Sarah later built the same logic in OrderServiceAMImpl.getCashierName().
     * Both do the same thing. Both are used.
     */
    public String getFullName() {
        return getAttribute(FIRST_NAME) + " " + getAttribute(LAST_NAME);
    }

    // Standard ADF getters/setters - generated by JDeveloper wizard
    public String getEmployeeId() { return (String) getAttributeInternal(EMPLOYEE_ID); }
    public void setEmployeeId(String value) { setAttributeInternal(EMPLOYEE_ID, value); }

    public String getFirstName() { return (String) getAttributeInternal(FIRST_NAME); }
    public void setFirstName(String value) { setAttributeInternal(FIRST_NAME, value); }

    public String getLastName() { return (String) getAttributeInternal(LAST_NAME); }
    public void setLastName(String value) { setAttributeInternal(LAST_NAME, value); }

    public String getSsn() { return (String) getAttributeInternal(SSN); }
    public void setSsn(String value) { setAttributeInternal(SSN, value); }

    public String getIsActive() { return (String) getAttributeInternal(IS_ACTIVE); }
    public void setIsActive(String value) { setAttributeInternal(IS_ACTIVE, value); }

    // NOTE 2021: The "position" column was originally a job title like "Cashier".
    // In 2007 someone started using it for the POS terminal ID (completely different).
    // Now it sometimes holds a job title and sometimes a terminal ID.
    // The POS integration team and the HR team both use this field differently.
    // We can't split it because both teams' apps depend on the column being named "position".
    public String getPosition() { return (String) getAttributeInternal(POSITION); }
    public void setPosition(String value) { setAttributeInternal(POSITION, value); }

    @Override
    protected void create(AttributeList attributeList) {
        // Mike's create logic. Sets defaults just like PKG_STORE_OPS.hire_employee
        // EXCEPT: PKG_STORE_OPS generates employee_id with format BQ-EMP-XXXX.
        // This Java code does NOT generate the ID. The PL/SQL does.
        // If you create an employee through ADF without calling the stored procedure,
        // the employee_id will be null. This has happened. Multiple times.
        // See INC-2345, INC-2891, INC-3456.
        super.create(attributeList);
    }

    // ============================================================
    // DDL for reference (actual table: EMPLOYEES, created by Mike, 2000)
    // ============================================================
    // employee_id   VARCHAR2(10) PK
    // first_name    VARCHAR2(50)
    // last_name     VARCHAR2(50)
    // ssn           VARCHAR2(11)  -- plain text, known security issue
    // hire_date     DATE
    // store_number  VARCHAR2(5)
    // position      VARCHAR2(30)  -- ambiguous usage, see note above
    // hourly_rate   NUMBER(6,2)
    // manager_id    VARCHAR2(10)
    // phone         VARCHAR2(15)
    // is_active     CHAR(1)
}
