package model.entities;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.domain.Number;

/**
 * Order Entity Object
 * Created by: Sarah Mitchell, June 2003
 * Updated by: Jason Miller, April 2009 (added web order support)
 * Updated by: Agency Team, Feb 2012 (added loyalty fields)
 * Updated by: Delivery SWAT Team, March 2020 (added delivery_type)
 *
 * This EO has been modified by 4 different teams over 20 years.
 * Some fields are used by everyone. Some are used by only one integration.
 * It's unclear which fields are safe to remove.
 *
 * - Sarah (2003)
 * - Jason (2009): I added status values for web flow
 * - Dmitri (2012): Added loyalty_redemption_id (only used by LOYALTY_PKG)
 * - Dave (2020): Added delivery_type for pandemic delivery
 */
public class OrderEOImpl extends EntityImpl {

    // Sarah's attribute indices (she used shorter names than Mike)
    private static final int ORDER_ID = 0;
    private static final int STORE_ID = 1;
    private static final int ORDER_DT = 2;
    private static final int ORDER_TYPE = 3;
    private static final int TOTAL_AMOUNT = 4;
    private static final int TAX_AMOUNT = 5;
    private static final int PAYMENT_METHOD = 6;
    private static final int EMPLOYEE_ID = 7;
    private static final int STATUS = 8;

    // Jason added these virtual attributes in 2009. They're not in the DB table
    // but the ADF framework maps them through the View Object to display on the UI.
    // They only work if you use Jason's specific ViewObject. Sarah's original VO
    // doesn't have them. The FranchiseDashboardBean imports both and sometimes
    // gets null values because of this mismatch.
    private static final int ONLINE_ORDER_REF = 100;   // Virtual attr - not in DB
    private static final int LOYALTY_REDEMPTION_ID = 101; // Virtual attr - added 2012
    private static final int DELIVERY_TYPE = 102;      // Virtual attr - added 2020

    /**
     * Calculates the order total.
     *
     * IMPORTANT: This uses the ADF layer's calculation which is SLIGHTLY
     * different from sp_get_order_total (Sarah's PL/SQL, pre-tax) and
     * FRANCHISE_PKG.calculate_franchise_order_total (Raj, includes tax).
     *
     * This version includes tax but rounds DOWN instead of to nearest cent.
     * The 2-cent discrepancy was flagged by accounting in 2015. After weeks
     * of investigation, everyone agreed it was "close enough" and they
     * manually adjust during month-end close.
     */
    public Number getOrderTotal() {
        return (Number) getAttributeInternal(TOTAL_AMOUNT);
    }

    // Standard getters (generated by JDeveloper, edited by multiple people)
    public Number getOrderId() { return (Number) getAttributeInternal(ORDER_ID); }
    public void setOrderId(Number value) { setAttributeInternal(ORDER_ID, value); }

    public Number getStoreId() { return (Number) getAttributeInternal(STORE_ID); }
    public void setStoreId(Number value) { setAttributeInternal(STORE_ID, value); }

    public String getOrderType() { return (String) getAttributeInternal(ORDER_TYPE); }
    public void setOrderType(String value) { setAttributeInternal(ORDER_TYPE, value); }

    /**
     * Order status values over the years:
     * 2003: NEW, COMPLETED, CANCELLED (Sarah's originals)
     * 2009: Added WEB_ORDER (Jason)
     * 2012: Added MOBILE_ORDER (Wei)
     * 2020: Added DELIVERY, EN_ROUTE, DELIVERED, FAILED (Dave)
     *
     * Valid status transitions depend on which era's code is checking.
     * The UI doesn't enforce transitions - any status can go to any status.
     * We rely on stored procedures to enforce business rules.
     * The stored procedures were written by 6 different people.
     * They don't all agree on valid transitions.
     */
    public String getStatus() { return (String) getAttributeInternal(STATUS); }
    public void setStatus(String value) { setAttributeInternal(STATUS, value); }
}
